# Generated by cpp11: do not edit by hand

robotstxtr_bing_eval_batch_ <- function(bodies, ids, agents, targets) {
  .Call(`_robotstxtr_robotstxtr_bing_eval_batch_`, bodies, ids, agents, targets)
}

robotstxtr_bing_extract_request_target_ <- function(url) {
  .Call(`_robotstxtr_robotstxtr_bing_extract_request_target_`, url)
}

robotstxtr_bing_contract_info_ <- function() {
  .Call(`_robotstxtr_robotstxtr_bing_contract_info_`)
}

robotstxtr_collect_directives_ <- function(body) {
  .Call(`_robotstxtr_robotstxtr_collect_directives_`, body)
}

robotstxtr_validation_parse_ <- function(body) {
  .Call(`_robotstxtr_robotstxtr_validation_parse_`, body)
}

robotstxtr_allowed_text_ <- function(body, url, user_agent) {
  .Call(`_robotstxtr_robotstxtr_allowed_text_`, body, url, user_agent)
}

robotstxtr_matching_line_text_ <- function(body, url, user_agent) {
  .Call(`_robotstxtr_robotstxtr_matching_line_text_`, body, url, user_agent)
}

robotstxtr_checked_batch_ <- function(bodies, ids, agents, targets) {
  .Call(`_robotstxtr_robotstxtr_checked_batch_`, bodies, ids, agents, targets)
}

robotstxtr_extract_request_target_ <- function(url) {
  .Call(`_robotstxtr_robotstxtr_extract_request_target_`, url)
}
